### PR TITLE
React migration

### PR DESCRIPTION
**Pull request by bstafford2017**

### CODE REVIEW

**Comment by ahnafyy** [comment]
HOW LONG IS THIS MIGRATION GOING TO TAKE?

**Comment by bstafford2017** [comment]
> HOW LONG IS THIS MIGRATION GOING TO TAKE?

Once the eSC is retired, this PR will get merged...

**Review by ahnafyy — DISMISSED** [review]
Looks great 🧇

**Comment by bstafford2017** [comment]
> Looks great 🧇

@ahnafyy How do I enable CORS for my lambdas? ❌ #RIP

**Comment by ahnafyy** [comment]
```javascript
exports.BenjiLambda = async (event) => {
    const response = {
        statusCode: 200,
        headers: {
            "Access-Control-Allow-Headers" : "Content-Type",
            "Access-Control-Allow-Origin": "https://www.benji.com",
            "Access-Control-Allow-Methods": "OPTIONS,POST,GET"
        },
        body: JSON.stringify('BENJI!!'),
    };
    return response;
```

**Review by ahnafyyy — DISMISSED** [review]

**Comment by ahnafyy** [comment]
Looking good!

**Review by ahnafyy — DISMISSED** [review]

**Pull request merged**
